name: Notify Microsoft 365

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft 365
        run: |
          curl -H "Content-Type: application/json" -d "{ 'text': '안녕하세요^^' }" https://o365kopo.webhook.office.com/webhookb2/1cd0ea02-e65b-4af7-bf9a-a42e37ce31d2@ad21525c-fc0f-4dbc-a403-67ce00add0e4/IncomingWebhook/e5cebc81a54c49a6894a1260a5ac5bba/f148149e-e673-46b0-9b2e-078bde1fc819
